name: atas-challenge
recipe: laravel
config:
  webroot: app/public
services:
  node:
    type: php
    ports:
      - 5173:5173 # expose vite dev server
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
      - npm run install && npm run build
tooling:
  node:
    service: node
  npm:
    service: node
