name: atas-challenge
recipe: laravel
config:
  webroot: app/public
services:
  app:
    type: php
    ports:
      - 5173:5173 # expose vite dev server
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
tooling:
  node:
    service: app
  npm:
    service: app
events:
  post-start:
    - app: cd app && npm install && npm run build
